.\" Copyright Ximian, Inc. 2002. 
.\" Please visit bugzilla.ximian.com to report problems with the software or its documentation.
.TH "rc" "1" "1.0" "Aaron Weber <aaron@ximian.com>" "System tools"
.SH "NAME"
.LP 
rc \- rc is the command\-line interface to the Ximian Red Carpet daemon rcd.
.SH "SYNTAX"
.LP 
rc \fI[\-\-global\-options]\fR <command> \fI[\-\-command\-options]\fR <arguments>

.br 

rc \-\-version
.br 

rc \fI\-\-help\fR 
.SH "DESCRIPTION"
.LP 
rc is the command\-line complement to the Ximian Red Carpet software management tool.  It works with the rcd daemon to install, update, and remove software according to the commands you give it. The software which it installs can be from local files or from Ximian servers and mirrors, and the system where software is being managed can be a remote system (see the \-\-host option and the rcd(8) man page) rather than the local system running rc.
.LP 
Red Carpet services sort software by category into channels, groups of similar software. For example, one channel might contain software from the operating system vendor, and another the Ximian Desktop, and another one the Ximian Connector or some software from a third\-party software vendor. You can subscribe to individual channels to control the display of available packages and prevent the accidental installation of unwanted software. Operations are normally performed only on software from within channels to which you are subscribed, although you may alter this with the \fI\-\-allow\-unsubscribed\fR flag.
.LP 
Red Carpet services, including rc, use your operating system's native package management system (except on Solaris, where they use RPM), so you can use most other package management tools alongside them.
.SH "COMMANDS"
.LP 
rc provides a number of commands (shown as <\fIcommand\fR> in the SYNTAX section), each of which has a number of options in addition to the global options which affect all transactions. The most commonly used is \fIrc update\-all\fR which downloads and installs updates in channels to which you are subscribed. If you only want to update software, that is the only command you need.

.LP 
\fBPackage management commands:\fR
.LP 
Note that you may substitute standard shell wildcards in package names, although not in channel names.
.TP 
info \fI<packagename>\fR 
Show detailed information about a package. Multiple packages may be listed, separated by spaces.

.TP 
install \fI<packagename>\fR
Install the specified package or packages. Multiple packages may be listed, separated by spaces. If \fIpackagename\fR designates a package which you already have installed, but for which a newer version is available, the new version will be downloaded and installed.

.TP 
lock\-add (la) \fI<options>\fR <packagename>  \fI[<relation> <version>]\fR
Add a package lock rule. This prevents changes to the installation state of the package which are not specifically requested.  The package name can be specified individually, with wildcard patterns, or even with version number relations. For example, the command \fIrc lock\-add gnome*<2.0\fR would keep all GNOME packages below 2.0.

.TP 
lock\-delete (ld) \fI<options>\fR <lock\-number>
Delete the lock you specify by its number. You can find the numbers for each lock with the lock\-list (ll) command.

.TP 
lock\-list (ll) \fI<options>\fR [<relation> <version>]
List the locks that have been put in place. Locks are sorted by ID number.

.TP 
packages \fI<"channelname">\fR\fR
List the packages in a channel. If no channel is specified, all packages will be listed. If an ambiguous channel name is specified, specific channels will be suggested. You may use the full channel name or an alias. Multiple channel names may be used, separated by spaces.
 
.TP  
remove (rm, erase) \fI<packagename>\fR
Remove packages. Both \fIrm\fR and \fIerase\fR are equivalents.

.TP 
search \fI<querystring>\fR
Search for the query string in the list of packages.

.TP 
summary (sum)
Display a summary of available updates.

.TP 
list\-updates (lu) [channelname] [channelname]
List updates in subscribed channels. Adding channels as arguments will limit the list to those channels you specify.  If you are not subscribed to a channel, it will never have updates available, even if you name it here; you must subscribe to list updates.

.TP 
update (up) [channelname] [channelname]
Download and install updates.  With no arguments, this will get all updates for subscribed channels. To choose specific channels, list them as arguments, separated by spaces.  For single packages, use rc install. If you are not subscribed to a channel, it will never have updates available; you must subscribe to install updates. If you want to install or update software from a channel to which you are not subscribed, use rc install with the \-u option.

.TP 
verify
Verify system dependencies. If the system dependencies are not satisfied, rc will suggest the removal or installation of packages necessary to resolve the conflicts.

.LP 
\fBChannel commands:\fR
.TP 
channels (ch) 
List available channels

.TP 
subscribe (sub)\fI<channelname>\fR
Subscribe to a channel. You may use the full channel name or the alias.

.TP 
unsubscribe (unsub) \fI<channelname>\fR
Unsubscribe from a channel.  You may use the full channel name or its alias.

.LP 
\fBDependency analysis commands:\fR 
.TP 
info\-conflicts (ic) \fI<packagename>\fR
List all packages that conflict with \fIpackagename.\fR

.TP 
info\-provides (ip)  \fI<packagename>\fR
Display the functionality or libraries that a package provides. If you wish to specify a particular channel from which to get the package, use the syntax [channel alias + ':']<package name> as is described in the EXAMPLES section.

.TP 
info\-requirements (ir)  \fI<packagename>\fR
List the software that must be present before the package can be installed.  

.TP 
solvedeps (solve) \fI<string>\fR 
Install or remove software to meet package, application, or library, and can include version numbers or ranges. The ! operator is used to indicate removal.  For example, the command rc solvedeps "!rpm\-python" "rpm404\-python" will remove the rpm\-python package, and replace it with the rpm404\-python package.

.TP 
what\-conflicts (wc) \fI<packagename>\fR
List packages that conflict with the item you specify.

.TP 
what\-provides (wp) \fI<querystring>\fR
List packages that provide the library, program, or package that you specify.

.TP 
what\-requires (wr)  \fI<querystring>\fR       
List packages that require the library, program, or package you specify.

.LP 
\fBPreference management commands:\fR 
.TP 
get\-prefs (get, prefs)\fR   
List the system preferences that may be set.

.TP 
set\-prefs (set) \fI<key>  \fI<value>\fR         
Set the preference variable \fIkey\fRto the value \fI<value>\fR.

.LP 
\fBSystem commands:\fR
.br 
.TP 
activate (act)<activation code> <email address>
Activates the machine for a premium server, allowing it access to private channels hosted there.

.TP 
dump
Get an XML dump of system information. Usually used for debugging purposes; the output of this command is best directed to a file and compressed.

.TP 
mount <path>
Mount a directory as a channel, adding all packages within the directory to the channel. The platform for the channel is assumed to be the same as the platform of the server.

.TP 
ping \fI<servername>\fR 
Ping the rcd process on the server. If no server is specified, the current server will be pinged.

.TP 
refresh
Refresh channel data for all channels.
.TP 
shutdown
Halt the server's rcd process.
.TP 
unmount <channel>
Unmount a directory that has been mounted as a channel.

.LP 
\fBUser management commands:\fR 
.TP 
user\-add
Create an account with the Red Carpet Daemon so that someone can manage software on your system without logging into it directly. This command can also be used to grant administration access to non\-root local users.

.TP 
user\-delete  \fI<username>\fR
Delete a specific user.

.TP 
user\-list
List the users that may update your system software.

.LP 
\fBOther commands:\fR 
.TP 
help \fI<command>\fR
Get detailed help on a command. If no command is specified, displays a list of all of the available commands.

.TP 
history \fI<packagename>\fR     
Search log entries for the package you specify.

.TP 
news
.br 
Display the Red Carpet news.
.br 
.SH "GLOBAL OPTIONS"
.LP 
The following options can be applied to any rc transaction:
.TP 
\fB\-\-batch\fR
Run in batch mode.

.TP 
\fB\-\-debug\fR
Print extra debugging information while running. This is different from the debug command, which collects a coredump.

.TP 
\fB\-h, \-\-host=<\fIhostname\fB>\fR
Specify the host system where the transaction will be performed. The host system must be running the rcd daemon.

.TP 
\fB\-\-help\fR
Used without a command, this flag displays a list of commands and exits. Used with a command, it displays a list of available options for the command.

.TP 
\fB\-\-ignore\-env\fR
Ignore the RC_ARGS environment variable for this transaction.

.TP 
\fB\-\-ignore\-rc\-file\fR
Ignore settings in the .rcrc file when running the transaction.

.TP 
\fB\-N, \-\-dry\-run\fR
Do not perform the actual transaction, but print what would have been done.

.TP 
\fB\-\-normal\-output\fR
Normal output (the default mode). This is somewhere between "verbose" and "terse."

.TP 
\fB\-P, \-\-password <password\fR
Specify password to be used.

.TP 
\fB\-q, \-\-quiet\fR
Quiet output: print only error messages. 

.TP 
\fB\-\-read\-from\-file <filename>\fR
Get additional arguments from the file you specify.

.TP 
\fB\-\-read\-from\-stdin\fR
Get arguments from stdin.

.TP 
\fB\-t, \-\-terse\fR
Terse output.

.TP 
\fB\-U, \-\-user, <username>\fR
Specify a user name for this transaction.

.TP 
\fB\-V, \-\-verbose\fR
Verbose mode; displays extra information for the transaction, if any is available.

.TP 
\fB\-\-version\fR
Displays the version number of the program and exits.


.SH "COMMAND OPTIONS"
.LP 
Many rc commands have options which apply only to them.  They are listed here alphabetically.

.TP 
\fBrc activate (act)\fR
.B \fI\-n, \-\-no\-refresh\fR: Do not refresh the channel data after activation.

.TP 
\fBrc channels (ch)\fR
.B \fI\-s, \-\-subscribed\fR: List only channels to which you are subscribed.
.br 
.B \fI\-u, \-\-unsubscribed\fR: List only channels to which you are not subscribed.

.TP 
\fBrc history\fR <\fIquerystring\fR>\fR
.B \fI\-n, \-\-search\-name\fR: Search logs by package name (default).
.br 
.B \fI\-a, \-\-search\-action\fR: Search logs by action performed.
.br 
.B \fI\-\-search\-host\fR: Search logs by host used.
.br 
.B \fI\-\-search\-user\fR: Search by user performing actions.
.br 
.B \fI\-\-match\-all\fR: Search only for a match for all search strings (default).
.br 
.B \fI\-\-match\-any\fR: Display results that match any search string.
.br 
.B \fI\-\-match substrings\fR: Display results that match substrings against any part of a word.
.br 
.B \fI\-\-match\-words\fR: Search only for a match on a complete word.
.br 
.B \fI\-d, \-\-days\-back=<number_of_days>\fR: Maximum number of days to look back in the logs (default is 30).
.br 

.TP 
\fBrc info\fR <\fIpackagename\fR>\fR
.B \fI\-u, \-\-allow\-unsubscribed\fR: Search in channels to which you are not subscribed, as well as subscribed channels.

.TP 
\fBrc install\fR <\fIpackagename\fR>\fR
.B \fI\-d, \-\-download\-only\fR: Downloads the packages, but does not install them. See also the \-N or \-\-dry\-run flag, which is available for all commands.
.br 
.B \fI\-r, \-\-allow\-removals\fR: Permit rc to remove software without confirmation.
.br 
.B \fI\-y, \-\-no\-confirmation\fR: Permit all actions without confirmation.
.br 
.B \fI\-r, \-\-allow\-removals\fR: Allow software to be removed as necessary to complete the installation..br 
.B \fI\-u, \-\-allow\-unsubscribed\fR: Allow required software to be pulled in from channels to which you are not subscribed.

.TP 
\fBrc lock\-add\fR 
.B \fI\-c, \-\-channel=\fI<channel>\fR: Specify a channel to match.

.B \fI\-i, \-\-importance=\fI<importance>\fR: Set the minimum importance level for the lock. Packages less important than the importance level you specify will be blocked, and those that are at least as important will be updated without the need to override. Possible importance levels, from least to most important, are: minor, feature, suggested, urgent, necessary.

.TP 
\fBrc lock\-delete\fR 
.B \fI\-\-\-no\-confirmation: Permit removals without confirmation

.TP 
\fBrc lock\-list\fR 
.B \fI\-\-no\-abbrev: Do not abbreviate channel information.
.B \fI\-m \-\-matches: Show information about matching packages.

.TP 
\fBrc news\fR \fR
.B  \fI\-c, \-\-channel=<channel>\fR: Show news only for the channel you specify.
.br 
.B  \fI\-s, \-\-subscribed\-only\fR: Only show news related to subscribed channels.
.br 
.B  \fI\-u, \-\-unsubscribed\-only\fR: Show news only for channels to which you are not subscribed.

.TP 
\fBrc list\-updates (lu)\fR
.B \fI\-\-no\-abbrev\fR: Do not abbreviate channel or version information.
.B \fI\-\-sort\-by\-name\fR: Sort packages by name (default).
.br 
.B \fI\-\-sort\-by\-channel\fR: Sort packages by channel.

.TP 
\fBrc mount\fR
.B \fI\-a, \-\-alias\fR: Alias for the new channel. If one is not provided, it will be the same as the name of the directory.
.B \fI\-n, \-\-name\fR: Name for new channel. If one is not provided, it will be the same as the alias.

.TP 
\fBrc packages\fR <\fIchannelname\fR>
.B \fI\-\-no\-abbrev\fR: Do not abbreviate channel or version information.
.br 
.B \fI\-\-sort\-by\-name\fR: Sort packages by name (default).
.br 
.B \fI\-\-sort\-by\-channel\fR: Sort packages by channel.

.TP 
\fBrc remove\fR <\fIpackagename\fR>
.B \fI\-y, \-\-no\-confirmation\fR: Perform the actions with no confirmation.

.TP 
\fBrc search\fR <\fIquerystring\fR>
.TP 
Seach String Options:
.B \fI\-\-match\-all\fR: Search only for a match for all search strings (default).
.br 
.B \fI\-\-match\-any\fR: Display results that match any search string.
.br 
.B \fI\-\-match substrings\fR: Display results that match substrings against any part of a word (default).
.br 
.B \fI\-\-match\-words\fR: Search only for a match on a complete word.

.br 
.TP 
Search Data Options:
.B \fI\-\-search\-description\fR: Search only in the package description, not in the package names.
.br 
.B \fI\-i, installed\-only\fR: Search only in the installed packages.
.br 
.B \fI\-u, \-\-uninstalled\-only\fR: Search only among packages which are not installed.
.br 
.B \fI\-c, \-\-channel=<channel>\fR: Search only in the channel you specify.
.TP 
Output Options:
.B \fI\-show\-package\-ids\fR: Show package IDs.
.br 
.B \fI\-\-sort\-by\-name\fR: Sort packages by name (default).
.br 
.B \fI\-\-sort\-by\-channel\fR: Sort packages by channel.
.B \fI\-\-no\-abbrev\fR: Do not abbreviate channel or version information.
.br 

.TP 
\fBrc subscribe (sub)\fR <\fIchannel>\fR
.B \fI\-s, \-\-strict\fR: Fail if attempting to subscribe to a channel to which you already subscribe.

.TP 
\fBrc summary (sum)\fR
.B \fI\-\-no\-abbrev\fR: Do not abbreviate channel names or importance levels.

.TP 
\fBrc update (up)\fR <\fIchannel\fR>
.B \fI\-N, \-\-dry\-run\fR: Do not actually perform requested actions
.br 
.B \fI\-y, \-\-no\-confirmation\fR: Permit all actions without confirmations
.br 
.B \fI\-d, \-\-allow\-removals\fR: Permit removal of software without confirmation
.br 
.B \fI\-i, \-\-importance=<importance>\fR: Only install updates as or more important than the value you specify. Value may be 'minor', 'feature', 'suggested', 'necessary', or 'urgent'. 
.br 
.B \fI\-r, \-\-allow\-removals\fR: Allow software to be removed as necessary to complete the installation..br 

.TP 
\fBrc unsubscribe (unsub)\fR <\fIchannel\fR>
.B \fI\-s, \-\-strict\fR: Fail if attempting to unsubscribe from a channel to which you are not subscribed.

.TP 
\fBrc user\-add\fR
.B \fI\-P\fR: Specify the password for this user.
.B \fI\-U\fR: Specify the user name for this user.

.TP 
\fBrc verify\fR
.B \fI\-d, \-\-allow\-removals\fR: Permit rc to remove software without confirmation.
.br 
.B \fI\-y, \-\-no\-confirmation\fR: Permit all actions without confirmation.

.TP 
\fBrc what\-conflicts\fR <\fIpackagename\fR>
.B \fI\-\-no\-abbrev\fR: Do not abbreviate channel or version information.
.B \fI\-i, installed\-only\fR: Search only in the installed packages.
.br 
.B \fI\-u, \-\-uninstalled\-only\fR: Search only among packages which are not installed.
.B \fI\-\-sort\-by\-name\fR: Sort packages by name (default).
.br 
.B \fI\-\-sort\-by\-channel\fR: Sort packages by channel.

.TP 
\fBrc what\-provides\fR <\fIquerystring\fR>\fR 
.B \fI\-\-no\-abbrev\fR: Do not abbreviate channel or version information.
.B \fI\-i, installed\-only\fR: Search only in the installed packages.
.br 
.B \fI\-u, \-\-uninstalled\-only\fR: Search only among packages which are not installed.
.B \fI\-\-sort\-by\-name\fR: Sort packages by name (default).
.br 
.B \fI\-\-sort\-by\-channel\fR: Sort packages by channel.

.TP 
\fBrc what\-requires\fR <\fIquerystring\fR>\fR 
.B \fI\-\-no\-abbrev\fR: Do not abbreviate channel or version information.
.B \fI\-i, installed\-only\fR: Search only in the installed packages.
.br 
.B \fI\-u, \-\-uninstalled\-only\fR: Search only among packages which are not installed.
.B \fI\-\-sort\-by\-name\fR: Sort packages by name (default).
.br 
.B \fI\-\-sort\-by\-channel\fR: Sort packages by channel.

.SH "FILES"
.TP 
 \fI.rcrc\fR

  The \fI.rcrc\fR resource file is optional. If it exists, its contents are treated as additional arguments to the rc command being executed.  This is similar to the behavior of the RC_ARGS environment variable.  Note also that the .rcrc file used is in the home directory of the user running rc, and if you run rc through sudo instead of directly as root, you will not use the root user's .rcrc file.
.SH "ENVIRONMENT VARIABLES"
.TP 
\fBRC_ARGS\fP
This environment variable is prepended to any
command line options that are passed to rc and acts as an extra set of arguments.  The variable is ignored if the \fI\-\-ignore\-env\fR flag is set. Do not attempt to set the \fI\-\-ignore\-env\fR flag in the RC_ARGS variable; this is absurd.
.SH "EXAMPLES"
.LP 
In most cases, non\-root users will be able to query the system but not alter it. However, system administrators may use the user\-add (ua) command to create rcd accounts for non\-root users if they wish.
 
Note that rc will use the .rcrc file in the home directory of the user running the program, and that putting the file just in root's home directory will not ensure that it is used every time.

.LP 
Here are some standard ways in which the program might be used:
.TP 
\fBrc update \-y\fR
Download and install all updates to currently installed package in currently subscribed channels, removing any software that conflicts with those updates, and without asking for confirmation. This is convenient option but should be used only with servers which you trust absolutely.

.TP 
\fBrc \-Vu \-\-host=\fI<hostname>\fB install \fI<packagename>\fR
This will operate in verbose mode and contact the rcd daemon on the specified host to install the specified package, regardless of whether it is in a channel to which the user is subscribed.

.TP 
\fBrc solvedeps \fI"library.so.1" "application < 1.2"\fR
Installs the package that provides \fIlibrary.so.1\fR and a version of \fIapplication\fR lower than 1.2.

.TP 
\fBrc info\-provides mychannel:mypackage</fR>
Displays the functionality provided by the "mypackage" software from "mychannel."

.TP 
\fBrc install rc*\fR
Installs all packages that are in subscribed channels whose names begin with "rc".
.SH "AUTHORS"
.LP 
Copyright 2002 Ximian, Inc.
http://www.ximian.com/
.SH "SEE ALSO"
.LP 
rcd(8), rcd.conf(5), rcman(1), rcreports, rc\-dump, rc\-restore, rce\-getchannels(1), red\-carpet(GNOME application), 
.LP 
The graphical Red Carpet client, red\-carpet, has a manual accessible through the GNOME help system; select items from the Help menu within the application to read it. Visit http://ximian.com for more information about rc, the Ximian Red Carpet family of products and services, and other software from Ximian. To report problems with this software or its documentation, visit http://bugzilla.ximian.com.
