.\" Copyright (C) Ximian, Inc. 2002-2003. 
.\" Please visit bugzilla.ximian.com to report problems with the software or its documentation.
.TH "rug" "1" "1.0" "Ximian, Inc." "Ximian Red Carpet Software Management Tools"
.SH "NAME"
.LP 
rug \- rug is the command\-line interface to the Ximian Red Carpet Daemon, rcd.
.SH "SYNTAX"
.LP 
rug \fI[\-\-global\-options]\fR <command> \fI[\-\-command\-options]\fR <arguments>

.br 

rug \-\-version
.br 

rug \fI\-\-help\fR 
.SH "DESCRIPTION"
.LP 
rug is the command\-line complement to the Ximian Red Carpet software management tool.  It works with the rcd daemon to install, update, and remove software according to the commands you give it. The software which it installs can be from local files or from Ximian servers and mirrors, and the system where software is being managed can be a remote system (see the \-\-host option and the rcd(8) man page) rather than the local system running rug. You may use one or more remote servers, known as services.
.LP 
Red Carpet applications sort software by category into channels, groups of similar software. For example, one channel might contain software from the operating system vendor, and another the Ximian Desktop, and another one the Ximian Connector or some software from a third\-party software vendor. You can subscribe to individual channels to control the display of available packages and prevent the accidental installation of unwanted software. Operations are normally performed only on software from within channels to which you are subscribed, although you may alter this with the \fI\-\-allow\-unsubscribed\fR flag.
.LP 
Red Carpet applications, including rug, use your operating system's native package management system (except on Solaris, where they use RPM), so you can use most other package management tools alongside them.
.LP 
Note: Previous versions of this software were known as \fIrc\fR, but due to a conflict with another package the application has been renamed. Other related software names, such as rcd, rcman, and red\-carpet, have not been affected. The \fIrug\fR command now uses the \fI.rugrc\fR configuration file and the \fIRUG_ARGS\fR environment variable. The older \fI.rcrc\fR and \fIRC_ARGS\fR are accepted if the new forms are absent.
.SH "COMMANDS"
.LP 
rug provides a number of commands (shown as <\fIcommand\fR> in the SYNTAX section), each of which has a number of options in addition to the global options which affect all transactions. The most commonly used is \fIrug update\fR which downloads and installs updates in channels to which you are subscribed. If you only want to update software, that is the only command you need.

.LP 
\fBPackage management commands:\fR
.LP 
Note that you may substitute standard shell wildcards in package names, although not in channel names.
.TP 
info \fI<packagename>\fR 
Show detailed information about a package. Multiple packages may be listed, separated by spaces.

.TP 
install \fI<packagename>\fR
Install the specified package or packages. Multiple packages may be listed, separated by spaces. If \fIpackagename\fR designates a package which you already have installed, but for which a newer version is available, the new version will be downloaded and installed.

.TP 
lock\-add (la) \fI<options>\fR <packagename>  \fI[<relation> <version>]\fR
Add a package lock rule. This prevents changes to the installation state of the package which are not specifically requested.  The package name can be specified individually, with wildcard patterns, or even with version number relations. For example, the command \fIrug lock\-add gnome*<2.0\fR would keep all GNOME packages below 2.0.

.TP 
lock\-delete (ld) \fI<options>\fR <lock\-number>
Delete the lock you specify by its number. You can find the numbers for each lock with the lock\-list (ll) command.

.TP 
lock\-list (ll) \fI<options>\fR [<relation> <version>]
List the locks that have been put in place. Locks are sorted by ID number.

.TP 
packages \fI<"channelname">\fR\fR
List all packages in a channel. If no channel is specified, all installed packages will be listed. If an ambiguous channel name is specified, specific channels will be suggested. You may use the full channel name or an alias. Multiple channel names may be used, separated by spaces.
<LI>
The output for this command is in three columns. The first column indicates the status, the second the name of the package, and the third the version of the package. The package status column will be empty if the package is not installed, and will show "i" if the package is installed, or "v" if the package is installed but is a different version from the one displayed in the list. If a package is locked (see the entries for the rug commands lock\-add, lock\-delete, and lock\-list), the status column will also display an L.
 
.TP  
remove (rm, erase) \fI<packagename>\fR
Remove packages. Both \fIrm\fR and \fIerase\fR are equivalents.

.TP 
rollback (ro) \fI[options] <packagename>\fR
Downgrade to the previous version of a package. To use this command you must use "rug set" to set the "repackage" variable in the [System] section of rcd.conf to "true" (see rcd.conf(5) for more information). Caveats: this feature only works on systems using RPM version 4.0.4 or greater,  will cause upgrades and removals to be very slow, and uses significant amounts of disk space.

.TP 
search \fI<querystring>\fR
Search for the query string in the list of packages.

.TP 
summary (sum)
Display a summary of available updates.

.TP 
list\-updates (lu) [channelname] [channelname]
List updates in subscribed channels. Adding channels as arguments will limit the list to those channels you specify.  If you are not subscribed to a channel, it will never have updates available, even if you name it here; you must subscribe to list updates.

.TP 
update (up) [channelname] [channelname]
Download and install updates.  With no arguments, this will get all updates for subscribed channels. To choose specific channels, list them as arguments, separated by spaces.  For single packages, use rug install. If you are not subscribed to a channel, it will never have updates available; you must subscribe to install updates. If you want to install or update software from a channel to which you are not subscribed, use rug install with the \-u option.

.TP 
verify
Verify system dependencies. If the system dependencies are not satisfied, rug will suggest the removal or installation of packages necessary to resolve the conflicts.

.LP 
\fBChannel commands:\fR
.TP 
channels (ch) 
List available channels. Output is in three columns: The first indicating whether you are subscribed to the channel, the second showing the short alias for the channel, and the third showing the full channel name.

.TP 
subscribe (sub)\fI<channelname>\fR
Subscribe to a channel. You may use the full channel name or the alias.

.TP 
unsubscribe (unsub) \fI<channelname>\fR
Unsubscribe from a channel.  You may use the full channel name or its alias.

.LP 
\fBDependency analysis commands:\fR 

.TP 
dangling\-requires
This command takes no arguments or options, and designed more for administrators to check the coherence of shipped software. It walks across all packages in all channels on the server, to see if there are any dependencies that are not provided by something else on the server. 

.TP 
info\-conflicts (ic) \fI<packagename>\fR
List all packages that conflict with \fIpackagename.\fR

.TP 
info\-provides (ip)  \fI<packagename>\fR
Display the functionality or libraries that a package provides. If you wish to specify a particular channel from which to get the package, use the syntax [channel alias + ':']<package name> as is described in the EXAMPLES section.

.TP 
info\-requirements (ir)  \fI<packagename>\fR
List the software that must be present before the package can be installed.  

.TP 
solvedeps (solve) \fI<string>\fR 
Install or remove software to meet package, application, or library, and can include version numbers or ranges. The ! operator is used to indicate removal.  For example, the command rug solvedeps "!rpm\-python" "rpm404\-python" will remove the rpm\-python package, and replace it with the rpm404\-python package.

.TP 
what\-conflicts (wc) \fI<packagename>\fR
List packages that conflict with the item you specify.

.TP 
what\-provides (wp) \fI<querystring>\fR
List packages that provide the library, program, or package that you specify.

.TP 
what\-requires (wr)  \fI<querystring>\fR       
List packages that require the library, program, or package you specify.

.LP 
\fBPreference management commands:\fR 
.TP 
get\-prefs (get, prefs)\fR   
List the system preferences that may be set.

.TP 
set\-prefs (set) \fI<key> <value>\fR         
Set the preference variable \fIkey\fR to the value \fI<value>\fR. Options are normally stored in the rcd.conf file (see rcd.conf(5) for more information), and can be changed by editing that file directly. However, additional Red Carpet modules can create additional settings which are not necessarily kept in rcd.conf but which are still set with the rug set.  The base set of options is:
.IP                                             
\fBenable\-premium:\fR If the value is true, the server is an Enterprise, CorporateConnect, or Express server.
.IP      
\fBproxy\-url:\fR URL for the proxy server, if any.
.IP 
\fBproxy\-username:\fR Username for the proxy, if any.
.IP 
\fBproxy\-password:\fR Password for the proxy, if any.                             
.IP 
\fBhttp\-1.0:\fR Use the HTTP/1.0 protocol for communications with the server. Defaults to False.
.IP 
\fBcache\-enabled:\fR If True, cache downloaded packages and metadata. Defaults is True.
.IP 
\fBcache\-directory:\fR The directory where cached data are stored. Default is /var/cache/redcarpet.
.IP 
\fBcache\-cleanup\-enabled:\fR Delete old packages from the cache. Default is True. 
.IP 
\fBcache\-max\-age\-in\-days:\fR The number of days to leave packages in the cache (if cache\-cleanup\-enabled is true). Default is 30.
.IP 
\fBcache\-max\-size\-in\-mb:\fR Maximum size of the cache before cleanup (if cleanup is enabled). Default is 300.
.IP 
\fBrequire\-signatures:\fR Require packages be signed before installing.         
.IP 
\fBheartbeat\-interval:\fR The interval in seconds between automatic refreshes of server data (in seconds). The default is 21600.
.IP 
\fBmax\-downloads:\fR Maximum number of concurrent package downloads. Default value is 5.
.IP 
\fBdebug\-level:\fR Sets the amount of debugging output to stderr. Values may be from 0 (none) to 6 (lots). The default is 4.
.IP 
\fBsyslog\-level:\fR Sets the amount of logging output saved in syslog. Values may be from 0 (none) to 6 (lots). The default is 4.
.IP 
\fBNote:\fR The "host" option is no longer present; use use the service\-add command instead.

.LP 
\fBSystem commands:\fR
.br 
.TP 
activate (act) \fI<activation code> <email address>\fR
Activates the machine for a premium server, allowing it access to private channels hosted there. If you use multiple servers, you must specify the server with the \fI\-s <URL>\fR flag. See the COMMAND OPTIONS section for more details.

.TP 
dump
Get an XML dump of system information. Usually used for debugging purposes; the output of this command is best directed to a file and compressed.

.TP 
mount <path>
Mount a directory as a channel, adding all packages within the directory to the channel. The platform for the channel is assumed to be the same as the platform of the server.

.TP 
mirrors
Choose a mirror from a list of available mirrors.

.TP 
ping \fI<servername>\fR 
Ping the rcd process on the server. If no server is specified, the current server will be pinged.

.TP 
recurring (rec)
Display information about recurring events, including both AutoPull and heartbeat (automatic channel refresh).  The command provides the label for the transaction, the total number of times it has occurred, and the date and time of the next and previous transactions. 

.TP 
refresh (ref)
Refresh channel data for all channels.

.TP 
service\-add (sa) \fI<url\-of\-server>\fR
Add a server to those that the daemon will check for updates. You may add multiple servers, and the daemon will connect to each one during when it refreshes. Server information is stored in the file /var/lib/rcd/services.xml.  If you are upgrading from rug 1.4 and do not have a services.xml file, your host entry will be read from rcd.conf once and only once, and then stored in services.xml. Editing services.xml by hand is not recommended.

.TP 
service\-list (sl)
List the servers which rcd will contact.

.TP 
service\-delete (sd) \fI<url\-of\-server>\fR
Delete a server from the list of those that the daemon will check for updates. 

.TP 
shutdown
Halt the server's rcd process.
.TP 
unmount <channel>
Unmount a directory that has been mounted as a channel.

.LP 
\fBUser management commands:\fR 
.TP 
user\-add (ua) [username] [privileges]
Create an account with the Red Carpet Daemon so that someone can manage software on your system without logging into it directly. This command can also be used to grant administration access to non\-root local users. You may provide the username and the names of privileges to be granted as arguments. If you do not, you will be prompted for them. After adding the user, it starts the user\-update tool to set privileges. To quit, press \fBEnter\fR on a blank line. See the EXAMPLES section for an example of how to use this command.

.TP 
user\-delete (ud) \fI<username>\fR
Delete a specific user.

.TP 
user\-edit (ue) \fI<username>\fR
Display a list of the user's privileges. This command is interactive: it will first list the privileges, then offer you a prompt. Enter the plus (+) or minus (\-) symbol and then the name of the privilege, then press \fBEnter\fR. For example, to permit the user to install software, you would type \fB+install\fR.  To save and quit, press \fBEnter\fR on a blank line. 

.TP 
user\-list (ul)
List the users known to the daemon.


.LP 
\fBOther commands:\fR 
.TP 
help \fI<command>\fR
Get detailed help on a command. If no command is specified, displays a list of all of the available commands.

.TP 
history \fI<packagename>\fR     
Search log entries for the package you specify.

.TP 
news
.br 
Display the Red Carpet news.
.br 
.SH "GLOBAL OPTIONS"
.LP 
The following options can be applied to any rug transaction:
.TP 
\fB\-\-batch\fR
Run in batch mode.

.TP 
\fB\-\-debug\fR
Print extra debugging information while running. This is different from the debug command, which collects a coredump.

.TP 
\fB\-h, \-\-host=<\fIhostname\fB>\fR
Specify the host system where the transaction will be performed. The host system must be running the rcd daemon.

.TP 
\fB\-\-help\fR
Used without a command, this flag displays a list of commands and exits. Used with a command, it displays a list of available options for the command.

.TP 
\fB\-\-ignore\-env\fR
Ignore the RC_ARGS environment variable for this transaction.

.TP 
\fB\-\-ignore\-rc\-file\fR
Ignore settings in the .rugrc file when running the transaction.

.TP 
\fB\-N, \-\-dry\-run\fR
Do not perform the actual transaction, but print what would have been done.

.TP 
\fB\-\-normal\-output\fR
Normal output (the default mode). This is somewhere between "verbose" and "terse."

.TP 
\fB\-P, \-\-password <password\fR
Specify password to be used.

.TP 
\fB\-q, \-\-quiet\fR
Quiet output: print only error messages. 

.TP 
\fB\-\-read\-from\-file <filename>\fR
Get additional arguments from the file you specify.

.TP 
\fB\-\-read\-from\-stdin\fR
Get arguments from stdin.

.TP 
\fB\-t, \-\-terse\fR
Terse output.

.TP 
\fB\-U, \-\-user, <username>\fR
Specify a user name for this transaction.

.TP 
\fB\-V, \-\-verbose\fR
Verbose mode; displays extra information for the transaction, if any is available.

.TP 
\fB\-\-version\fR
Displays the version number of the program and exits.


.SH "COMMAND OPTIONS"
.LP 
Many rug commands have options which apply only to them.  They are listed here alphabetically.

.TP 
\fBrug activate (act)\fR
.B \fI\-n, \-\-no\-refresh\fR: Do not refresh the channel data after activation.
.B \fI\-s, \-\-service\fR: If you are using multiple servers, use this flag to specify which one. Follow the flag with a space and the full URL of the server.
.B \fI\-a, \-\-alias\fR: Specify the alias for this machine; the alias is displayed to the server administrator. This option is useful only with Red Carpet Enterprise servers.

.TP 
\fBrug channels (ch)\fR
.B \fI\-s, \-\-subscribed\fR: List only channels to which you are subscribed.
.br 
.B \fI\-u, \-\-unsubscribed\fR: List only channels to which you are not subscribed.

.TP 
\fBrug history\fR <\fIquerystring\fR>\fR
.B \fI\-n, \-\-search\-name\fR: Search logs by package name (default).
.br 
.B \fI\-a, \-\-search\-action\fR: Search logs by action performed.
.br 
.B \fI\-\-search\-host\fR: Search logs by host used.
.br 
.B \fI\-\-search\-user\fR: Search by user performing actions.
.br 
.B \fI\-\-match\-all\fR: Search only for a match for all search strings (default).
.br 
.B \fI\-\-match\-any\fR: Display results that match any search string.
.br 
.B \fI\-\-match substrings\fR: Display results that match substrings against any part of a word.
.br 
.B \fI\-\-match\-words\fR: Search only for a match on a complete word.
.br 
.B \fI\-d, \-\-days\-back=<number_of_days>\fR: Maximum number of days to look back in the logs (default is 30).
.br 

.TP 
\fBrug info\fR <\fIpackagename\fR>\fR
.B \fI\-u, \-\-allow\-unsubscribed\fR: Search in channels to which you are not subscribed, as well as subscribed channels.

.TP 
\fBrug install\fR <\fIpackagename\fR>\fR
.B \fI\-d, \-\-download\-only\fR: Downloads the packages, but does not install them. See also the \-N or \-\-dry\-run flag, which is available for all commands.
.br 
.B \fI\-r, \-\-allow\-removals\fR: Permit rug to remove software without confirmation.
.br 
.B \fI\-y, \-\-no\-confirmation\fR: Permit all actions without confirmation.
.br 
.B \fI\-r, \-\-allow\-removals\fR: Allow software to be removed as necessary to complete the installation..br 
.br 
.B \fI\-u, \-\-allow\-unsubscribed\fR: Allow required software to be pulled in from channels to which you are not subscribed.
.br 
.B \fI\-\-entire\-channel\fR<\fIpackagename\fR>: Install all packages in the channel specified. For example, \fIrug \-\-entire\-channel install ximian\-gnome\fR would install everything in the entire "ximian\-gnome" channel.

.TP 
\fBrug lock\-add\fR 
.B \fI\-c, \-\-channel=\fI<channel>\fR: Specify a channel to match.
.br 
.B \fI\-i, \-\-importance=\fI<importance>\fR: Set the minimum importance level for the lock. Packages less important than the importance level you specify will be blocked, and those that are at least as important will be updated without the need to override. Possible importance levels, from least to most important, are: minor, feature, suggested, urgent, necessary.

.TP 
\fBrug lock\-delete\fR 
.B \fI\-\-\-no\-confirmation: Permit removals without confirmation

.TP 
\fBrug lock\-list\fR 
.B \fI\-\-no\-abbrev: Do not abbreviate channel information.
.br 
.B \fI\-m \-\-matches: Show information about matching packages.

.TP 
\fBrug news\fR \fR
.B  \fI\-c, \-\-channel=<channel>\fR: Show news only for the channel you specify.
.br 
.B  \fI\-s, \-\-subscribed\-only\fR: Only show news related to subscribed channels.
.br 
.B  \fI\-u, \-\-unsubscribed\-only\fR: Show news only for channels to which you are not subscribed.

.TP 
\fBrug list\-updates (lu)\fR
.B \fI\-\-no\-abbrev\fR: Do not abbreviate channel or version information.
.br 
.B \fI\-\-sort\-by\-name\fR: Sort packages by name (default).
.br 
.B \fI\-\-sort\-by\-channel\fR: Sort packages by channel.

.TP 
\fBrug mount\fR
.B \fI\-a, \-\-alias\fR: Alias for the new channel. If one is not provided, it will be the same as the name of the directory.
.br 
.B \fI\-n, \-\-name\fR: Name for new channel. If one is not provided, it will be the same as the alias.

.TP 
\fBrug packages\fR <\fIchannelname\fR>

.B \fI\-\-no\-abbrev\fR: Do not abbreviate channel or version information.
.br 
.B \fI\-i, \-\-installed\-only \fR:   Show only installed packages. This is the default behavior if no channel is specified.
.br 
.B \fI\-u, \-\-uninstalled\-only\fR:  Show only uninstalled packages
.br 
.B \fI\-\-sort\-by\-name\fR: Sort packages by name (default).
.br 
.B \fI\-\-sort\-by\-channel\fR: Sort packages by channel.

.TP 
\fBrug remove\fR <\fIpackagename\fR>
.B \fI\-y, \-\-no\-confirmation\fR: Perform the actions with no confirmation.

.TP 
\fBrug rollback\fR <\fIpackagename\fR>
.B \fI\-N, \-\-dry\-run\fR: Do not actually perform requested actions
.br 
.B \fI\-y, \-\-no\-confirmation\fR: Permit all actions without confirmations
.br 
.B \fI\-d, \-\-allow\-removals\fR: Permit removal of software without confirmation

.TP 
\fBrug search\fR <\fIquerystring\fR>
.TP 
Seach String Options:
.B \fI\-\-match\-all\fR: Search only for a match for all search strings (default).
.br 
.B \fI\-\-match\-any\fR: Display results that match any search string.
.br 
.B \fI\-\-match substrings\fR: Display results that match substrings against any part of a word (default).
.br 
.B \fI\-\-match\-words\fR: Search only for a match on a complete word.

.br 
.TP 
Search Data Options:
.B \fI\-\-search\-description\fR: Search only in the package description, not in the package names.
.br 
.B \fI\-i, installed\-only\fR: Search only in the installed packages.
.br 
.B \fI\-u, \-\-uninstalled\-only\fR: Search only among packages which are not installed.
.br 
.B \fI\-c, \-\-channel=<channel>\fR: Search only in the channel you specify.
.TP 
Output Options:
.B \fI\-show\-package\-ids\fR: Show package IDs.
.br 
.B \fI\-\-sort\-by\-name\fR: Sort packages by name (default).
.br 
.B \fI\-\-sort\-by\-channel\fR: Sort packages by channel.
.br 
.B \fI\-\-no\-abbrev\fR: Do not abbreviate channel or version information.
.br 

.TP 
\fBrug subscribe (sub)\fR <\fIchannel>\fR
.B \fI\-s, \-\-strict\fR: Fail if attempting to subscribe to a channel to which you already subscribe.

.TP 
\fBrug summary (sum)\fR
.B \fI\-\-no\-abbrev\fR: Do not abbreviate channel names or importance levels.

.TP 
\fBrug update (up)\fR <\fIchannel\fR>
.B \fI\-N, \-\-dry\-run\fR: Do not actually perform requested actions
.br 
.B \fI\-y, \-\-no\-confirmation\fR: Permit all actions without confirmations
.br 
.B \fI\-d, \-\-allow\-removals\fR: Permit removal of software without confirmation
.br 
.B \fI\-i, \-\-importance=<importance>\fR: Only install updates as or more important than the value you specify. Value may be 'minor', 'feature', 'suggested', 'necessary', or 'urgent'. 
.br 
.B \fI\-r, \-\-allow\-removals\fR: Allow software to be removed as necessary to complete the installation..br 

.TP 
\fBrug unsubscribe (unsub)\fR <\fIchannel\fR>
.B \fI\-s, \-\-strict\fR: Fail if attempting to unsubscribe from a channel to which you are not subscribed.

.TP 
\fBrug verify\fR
.B \fI\-d, \-\-allow\-removals\fR: Permit rug to remove software without confirmation.
.br 
.B \fI\-y, \-\-no\-confirmation\fR: Permit all actions without confirmation.

.TP 
\fBrug what\-conflicts\fR <\fIpackagename\fR>
.B \fI\-\-no\-abbrev\fR: Do not abbreviate channel or version information.
.br 
.B \fI\-i, installed\-only\fR: Search only in the installed packages.
.br 
.B \fI\-u, \-\-uninstalled\-only\fR: Search only among packages which are not installed.
.br 
.B \fI\-\-sort\-by\-name\fR: Sort packages by name (default).
.br 
.B \fI\-\-sort\-by\-channel\fR: Sort packages by channel.

.TP 
\fBrug what\-provides\fR <\fIquerystring\fR>\fR 
.B \fI\-\-no\-abbrev\fR: Do not abbreviate channel or version information.
.br 
.B \fI\-i, installed\-only\fR: Search only in the installed packages.
.br 
.B \fI\-u, \-\-uninstalled\-only\fR: Search only among packages which are not installed.
.br 
.B \fI\-\-sort\-by\-name\fR: Sort packages by name (default).
.br 
.B \fI\-\-sort\-by\-channel\fR: Sort packages by channel.

.TP 
\fBrug what\-requires\fR <\fIquerystring\fR>\fR 
.B \fI\-\-no\-abbrev\fR: Do not abbreviate channel or version information.
.br 
.B \fI\-i, installed\-only\fR: Search only in the installed packages.
.br 
.B \fI\-u, \-\-uninstalled\-only\fR: Search only among packages which are not installed.
.br 
.B \fI\-\-sort\-by\-name\fR: Sort packages by name (default).
.br 
.B \fI\-\-sort\-by\-channel\fR: Sort packages by channel.

.SH "FILES"
.TP 
 \fI.rugrc\fR

The \fI.rugrc\fR resource file is optional. If it exists, its contents are treated as additional arguments to the rug command being executed.  This is similar to the behavior of the \fIRUG_ARGS\fR environment variable.  Note also that the \fI.rugrc\fR file used is in the home directory of the user running rc, and if you run rug through sudo instead of directly as root, you will not use the root user's \fI.rugrc\fR file.

.LP 
If \fI.rugrc\fR does not exist, the older \fI.rcrc\fR file is accepted instead.
.SH "ENVIRONMENT VARIABLES"
.TP 
\fBRUG_ARGS\fP
This environment variable is prepended to any command line options that are passed to rug and acts as an extra set of arguments.  The variable is ignored if the \fI\-\-ignore\-env\fR flag is set. Do not attempt to set the \fI\-\-ignore\-env\fR flag in the \fIRUG_ARGS\fR variable; this is absurd.

.LP 
If \fIRUG_ARGS\fR is not set, the \fIRC_ARGS\fR environment variable is accepted instead.
.SH "EXAMPLES"
.LP 
In most cases, non\-root users will be able to query the system but not alter it. However, system administrators may use the user\-add (ua) command to create rcd accounts for non\-root users if they wish.
 
Note that rug will use the .rugrc file in the home directory of the user running the program, and that putting the file just in root's home directory will not ensure that it is used every time.

.LP 
Here are some standard ways in which the program might be used:
.TP 
\fBrug update \-y\fR
Download and install all updates to currently installed package in currently subscribed channels, removing any software that conflicts with those updates, and without asking for confirmation. This is convenient option but should be used only with servers which you trust absolutely.

.TP 
\fBrug \-Vu \-\-host=\fI<hostname>\fB install \fI<packagename>\fR
This will operate in verbose mode and contact the rcd daemon on the specified host to install the specified package, regardless of whether it is in a channel to which the user is subscribed.

.TP 
\fBrug solvedeps \fI"library.so.1" "application < 1.2"\fR
Installs the package that provides \fIlibrary.so.1\fR and a version of \fIapplication\fR lower than 1.2.

.TP 
\fBrug info\-provides mychannel:mypackage</fR>
Displays the functionality provided by the "mypackage" software from "mychannel."

.TP 
\fBrug install rc*\fR
Installs all packages that are in subscribed channels whose names begin with "rc".

.TP 
\fBrug ua donna install\fR
Adds a user named "donna" with the install privilege. After entering this command, you will be prompted to create and confirm a password for donna, and then to confirm or change the privileges granted to her.
.SH "AUTHORS"
.LP 
Copyright (C) 2002\-2003 Ximian, Inc.
http://www.ximian.com/
.SH "SEE ALSO"
.LP 
rcd(8), rcd.conf(5), rcman(1), rcreports(1), rcmirror(1)
.LP 
The graphical Red Carpet client, red\-carpet, has a manual accessible through the GNOME help system; select items from the Help menu within the application to read it. Visit http://ximian.com for more information about rc, the Ximian Red Carpet family of products and services, and other software from Ximian. To report problems with this software or its documentation, visit http://bugzilla.ximian.com.
