.\" Copyright (C) Ximian, Inc. 2002-2003. 
.\" Please visit bugzilla.ximian.com to report problems with the software or its documentation.
.TH "rug" "1" "1.0" "Ximian, Inc." "Ximian Red Carpet Software Management Tools"
.SH "NAME"
.LP 
rug \- rug is the command\-line interface to the Ximian Red Carpet Daemon, rcd.
.SH "SYNTAX"
.LP 
rug [\fB\-\-global\-options\fR] [command] [\fB\-\-command\-options\fR] [arguments]

.br 

rug \-\-version
.br 

rug \fI\-\-help\fR 
.SH "DESCRIPTION"
.LP 
rug is the command\-line complement to the Ximian Red Carpet software management tool.  It works with the rcd daemon to install, update, and remove software according to the commands you give it. The software which it installs can be from local files or from Ximian servers and mirrors, and the system where software is being managed can be a remote system (see the \-\-host option and the rcd(8) man page) rather than the local system running rug. You may use one or more remote servers, known as services.
.LP 
Red Carpet applications sort software by category into channels, groups of similar software. For example, one channel might contain software from the operating system vendor, and another the Ximian Desktop, and another one the Ximian Connector or some software from a third\-party software vendor. You can subscribe to individual channels to control the display of available packages and prevent the accidental installation of unwanted software. Operations are normally performed only on software from within channels to which you are subscribed, although you may alter this with the \fI\-\-allow\-unsubscribed\fR flag.
.LP 
Red Carpet applications, including rug, use your operating system's native package management system (except on Solaris, where they use RPM), so you can use most other package management tools alongside them.
.LP 
Note: Previous versions of this software were known as \fIrc\fR, but due to a conflict with another package the application has been renamed. Other related software names, such as rcd, rcman, and red\-carpet, have not been affected. The \fIrug\fR command now uses the \fI.rugrc\fR configuration file and the \fIRUG_ARGS\fR environment variable. The older \fI.rcrc\fR and \fIRC_ARGS\fR are accepted if the new forms are absent.
.SH "COMMANDS"
.LP 
rug provides a number of commands (shown as [\fIcommand\fR] in the SYNTAX section). Each command accepts the option flags listed in the GLOBAL OPTIONS section. In addition, many commands have specific option flags, which are listed here.
.LP 
The most commonly used command is \fIrug update\fR which downloads and installs updates in channels to which you are subscribed. If you only want to update software, that is the only command you need.

.LP 
\fBPackage management commands:\fR
.LP 
Note that you may substitute standard shell wildcards in package names, although not in channel names.
.TP 
info [packagename]
Show detailed information about a package. Multiple packages may be listed, separated by spaces. Accepts the flag \fI\-u, \-\-allow\-unsubscribed\fR, to search in channels to which you are not subscribed, as well as subscribed channels.

.TP 
install (in) [packagename]
Install the specified package or packages. Multiple packages may be listed, separated by spaces. If \fIpackagename\fR designates a package which you already have installed, but for which a newer version is available, the new version will be downloaded and installed. 

If you need to specify channels when installing packages, prepend the channel name and a colon to the package. For example: \fBrug in evolution\-devel\-snapshots:evolution\fR will install the "evolution" package from the "evolution\-devel\-snapshots" channel. If you do not specify a channel, the newest package will be installed. If there are two equal versions, the package from the channel with the higher priority (set by the server administrator) will be installed.

The install command accepts the following option flags:
.IP 
\-d, \-\-download\-only
.br 
Downloads the packages, but does not install them. See also the \-N or \-\-dry\-run flag, which is available for all commands.

\-y, \-\-no\-confirmation
.br 
Install without confirmation. Does not allow removal of conflicting packages without confirmation; to permit removal of conflicts without confirmation use \-r as well.

r, \-\-allow\-removals
.br 
Permit software removal software without confirmation. Use care when combining with the \-y option. 

\-u, \-\-allow\-unsubscribed
.br 
Allow required software to be pulled in from channels to which you are not subscribed.

\-\-entire\-channel [channelname]
.br 
Install all packages in the channel specified. For example, \fBrug install \-\-entire\-channel ximian\-desktop\fR would install everything in the "ximian\-desktop" channel.

.TP 
lock\-add (la) [options] [packagename]  \fI[[relation] [version]]\fR
Add a package lock rule. This prevents changes to the installation state of the package which are not specifically requested.  The package name can be specified individually, with wildcard patterns, or even with version number relations. For example, the command \fIrug lock\-add gnome*<2.0\fR would refuse to install any packages beginning with 'gnome' that had versions above 2.0. Accepts the following additional flags:
.IP 
\-c, \-\-channel=[channel]
.br 
Specify a channel to match.

\-i, \-\-importance=[importance]
.br 
Set the minimum importance level for the lock. Packages less important than the importance level you specify will be blocked, and those that are at least as important will override the lock. Possible importance levels, from least to most important, are: minor, feature, suggested, urgent, and necessary.

.TP 
lock\-delete (ld) [options] [lock\-number]
Delete the lock you specify by its number. You can find the numbers for each lock with the lock\-list (ll) command. Accepts the flag \fI\-\-\-no\-confirmation\fR flag, to permit removals without confirmation.

.TP 
lock\-list (ll) [options]
List the locks that have been put in place. Locks are sorted by ID number. Accepts the option flags:
.IP 
\-\-no\-abbrev
.br 
Do not abbreviate channel information.

\-m, \-\-matches
.br 
Show information about matching packages.

.TP 
packages (pa) [channelname]
List all packages in a channel. If no channel is specified, all packages in all channels will be listed. You may use the full channel name or an alias. Multiple channel names may be used, separated by spaces.

The output for this command is in three columns. The first column indicates the status, the second the name of the package, and the third the version of the package. The package status column will be empty if the package is not installed, and will show "i" if the package is installed, or "v" if the package is installed but is a different version from the one displayed in the list. If a package is locked (see the entries for the rug commands lock\-add, lock\-delete, and lock\-list), the status column will also display an L.

Accepts the following options:
.IP 
\-\-no\-abbrev
.br 
Do not abbreviate channel or version information.

\-i, \-\-installed\-only
.br 
Show only installed packages.

\-u, \-\-uninstalled\-only
.br 
Show only uninstalled packages

\-\-sort\-by\-name
.br 
Sort packages by name (default).

\-\-sort\-by\-channel
.br 
Sort packages by channel.

.TP  
remove (rm, erase) [packagename]
Remove packages. Accepts the flag \fI\-y\fR or \fI\-\-no\-confirmation\fR, to perform the actions with no confirmation. To allow removals that accompany installs, use \fBrug install\fR with both the \fI\-y\fR and the \fI\-r\fR (\fI\-\-allow\-removal\fR) flags.

.TP 
rollback (ro) [options] [time]
Roll back package transactions to the time and date you specify. The time to which you roll back must be a time after you set the "rollback" option to "true" using \fBrug set\fR (see rcd.conf(5) for more information).  Rollback works only on RPM\-based systems. Versions to which you downgrade must be available on your Red Carpet Enterprise server.

.IP 
\-N, \-\-dry\-run
.br 
Test, but do not actually perform, the requested actions.

\-y, \-\-no\-confirmation
.br 
Do not ask for confirmation when downgrading. Removal of software that is not being downgraded will still require confirmation unless combined with the \fI\-r\fR flag.

\-r, \-\-allow\-removals
.br 
Permit removal of software without confirmation

\-d, \-\-download\-only
.br 
Download, but do not install, any software required for the downgrade.

.TP 
search [querystring]
Search for the query string in the list of packages. Accepts the following options:

.IP 
\fISeach String Options:\fR
.br 
\-\-match\-all
.br 
Search only for a match for all search term (default).

\-\-match\-any
.br 
Display results that match any search term.

\-\-match substrings
.br 
Display results that match substrings against any part of a word (default).

\-\-match\-words
.br 
Search only for a match on a complete word.

\-\-search\-description
.br 
Search only in the package description, not in the package names.

\-i, installed\-only
.br 
Search only in the installed packages.

\-u, \-\-uninstalled\-only
.br 
Search only among packages which are not installed.

\-c, \-\-channel=[channel]
.br 
Search only in the channel you specify.
.IP 
\fIOutput Options:\fR
\-\-show\-package\-ids
Show package IDs as well as package names.

\-\-sort\-by\-name
.br 
Sort packages by name (default).

\-\-sort\-by\-channel
.br 
Sort packages by channel.

\-\-no\-abbrev
.br 
Do not abbreviate channel or version information.

.TP 
summary (sum)
Display a summary of available updates. Accepts one flag: \fI\-\-no\-abbrev\fR, meaning do not abbreviate channel names or importance levels.

.TP 
list\-updates (lu) [channelname] [channelname]
List updates in subscribed channels. Adding channels as arguments will limit the list to those channels you specify.  If you are not subscribed to a channel, it will never have updates available, even if you name it here; you must subscribe to list updates. Accepts the flags:
.IP 
\-\-no\-abbrev
.br 
Do not abbreviate channel or version information.

\-\-sort\-by\-name
.br 
Sort packages by name (default).

\-\-sort\-by\-channel
.br 
Sort packages by channel.


.TP 
update (up) [channelname] [channelname]
Download and install updates.  With no arguments, this will get all updates for subscribed channels. To choose specific channels, list them as arguments, separated by spaces.  For single packages, use \fBrug install\fR instead. If you are not subscribed to a channel, it will never have updates available; you must subscribe to install updates. If you want to install or update software from a channel to which you are not subscribed, use \fBrug install \-u\fR.  Accepts the following option flags:
.IP 
\-N, \-\-dry\-run
.br 
Test and display, but do not actually perform, the requested actions.

\-y, \-\-no\-confirmation
.br 
Install packages without confirmation. Will not permit removal of conflicting packages without confirmation; to allow removal without confirmation, use \-r as well. 

\-i, \-\-importance=[importance]
.br 
Only install updates as or more important than the value you specify. Value may be 'minor', 'feature', 'suggested', 'necessary', or 'urgent'. 

\-r, \-\-allow\-removals
.br 
Allow software to be removed as necessary to complete the installation.

.TP 
verify    
.br 
Verify system dependencies. If the system dependencies are not satisfied, rug will suggest the removal or installation of packages necessary to resolve the conflicts. Accepts the flags:
.IP 
\-r, \-\-allow\-removals
.br 
Permit rug to remove software without confirmation.

\-y, \-\-no\-confirmation
.br 
Permit installation without confirmation. Use with \-r to permit all actions without confirmation.

.LP 
\fBChannel commands:\fR
.TP 
channels (ch) 
List available channels. Output is in three columns: The first indicating whether you are subscribed to the channel, the second showing the short alias for the channel, and the third showing the full channel name. Accepts the following extra flags:
.IP 
\-s, \-\-subscribed
.br 
List only channels to which you are subscribed.

\-u, \-\-unsubscribed
.br 
List only channels to which you are not subscribed.

.TP 
subscribe (sub) [channelname]
Subscribe to a channel. You may use the full channel name or the alias.  Use the \fI\-s\fR or \fI \-\-strict\fR flag to have the action fail if attempting to subscribe to a channel to which you already subscribe. 

.TP 
unsubscribe (unsub) [channelname]
Unsubscribe from a channel.  You may use the full channel name or its alias. Use the \fI\-s\fR or \fI \-\-strict\fR flag to have the action fail if you were already unsubscribed.

.LP 
\fBDependency analysis commands:\fR 

.TP 
dangling\-requires
Walks across all packages in all channels on the server, to see if there are any dependencies that are not provided by something else on the server. This command takes no arguments or options. It is typically used by Red Carpet Enterprise server administrators who wish to check the coherence of software available to a particular client machine.

.TP 
info\-conflicts (ic) [packagename]
List all packages that conflict with \fIpackagename.\fR

.TP 
info\-provides (ip)  [packagename]
Display the functionality or libraries that a package provides. If you wish to specify a particular channel from which to get the package, use the syntax [channel alias + ':'][package name] as is described in the EXAMPLES section.

.TP 
info\-requirements (ir) [packagename]
List the software that must be present before the package can be installed.  

.TP 
solvedeps (solve) [string]
Install or remove software to meet package, application, or library, and can include version numbers or ranges. The ! operator is used to indicate removal.  For example, the command \fBrug solvedeps "!rpm\-python" "rpm404\-python"\fR will remove the rpm\-python package, and replace it with the rpm404\-python package.

.TP 
what\-conflicts (wc) [packagename]
List packages that conflict with the item you specify. Accepts the following option flags:
.IP 
\-\-no\-abbrev
.br 
Do not abbreviate channel or version information.

\-i, installed\-only
.br 
Search only in the installed packages.

\-u, \-\-uninstalled\-only
.br 
Search only among packages which are not installed.

\-\-sort\-by\-name
.br 
Sort packages by name (default).

\-\-sort\-by\-channel
.br 
Sort packages by channel.

.TP 
what\-provides (wp) [querystring]
List packages that provide the library, program, or package that you specify.  Accepts the following option flags:
.IP 
\-\-no\-abbrev
.br 
Do not abbreviate channel or version information.

\-i, installed\-only
.br 
Search only in the installed packages.

\-u, \-\-uninstalled\-only
.br 
Search only among packages which are not installed.

\-\-sort\-by\-name
.br 
Sort packages by name (default).

\-\-sort\-by\-channel
.br 
Sort packages by channel.


.TP 
what\-requires (wr) [querystring]      
List packages that require the library, program, or package you specify.  Accepts the following option flags:
.IP 
\-\-no\-abbrev
.br 
Do not abbreviate channel or version information.

\-i, installed\-only
.br 
Search only in the installed packages.

\-u, \-\-uninstalled\-only
.br 
Search only among packages which are not installed.

\-\-sort\-by\-name
.br 
Sort packages by name (default).

\-\-sort\-by\-channel
.br 
Sort packages by channel.


.LP 
\fBPreference management commands:\fR 
.TP 
get\-prefs (get, prefs) [token]
Display the value of the preference token you name. If you do not provide a token, displays all preferences.

.TP 
set\-prefs (set) [token] [value]  
Set the preference variable \fItoken\fR to the value \fIvalue\fR. Options are normally stored in the rcd.conf file (see rcd.conf(5) for more information), and can be changed by editing that file directly. However, additional Red Carpet modules can create additional settings which are not necessarily kept in rcd.conf but which are still set with the rug set.  The base set of options is:
.IP                                             

.IP 
\fBbind\-ip:\fR For systems using more than one IP address, selects the address at which rcd will bind. Leave empty to bind to all addresses.                     
.IP 
\fBcache\-cleanup\-enabled:\fR Delete packages from the cache when it gets too large or too old. Default is True.
.IP 
\fBcache\-directory:\fR The directory where cached data are stored. Default is /var/cache/redcarpet. 
.IP 
\fBcache\-enabled:\fR If True, cache downloaded packages and metadata. Defaults is True.
.IP 
\fBcache\-max\-age\-in\-days:\fR The number of days to leave packages in the cache (if cache\-cleanup\-enabled is true). Default is 30.
.IP 
\fBcache\-max\-size\-in\-mb:\fR Maximum size of the cache before cleanup (if cleanup is enabled). Default is 300.
.IP 
\fBdebug\-level:\fR Sets the amount of debugging output to stderr. Values may be from 0 (none) to 6 (lots). The default is 4.
.IP 
\fBheartbeat\-interval:\fR The interval in seconds between automatic refreshes of channel and package data. The default is 21600. Note that this does not affect the transaction polling interval, which is set with the server\-poll\-interval token. 
.IP 
\fBhttp\-1.0:\fR Use the HTTP/1.0 protocol for communications with the server. Defaults to False.
.IP 
\fBmax\-downloads:\fR Maximum number of concurrent package downloads. Default value is 5.
.IP 
\fBproxy\-password:\fR Password for the proxy, if any.        
.IP      
\fBproxy\-url:\fR URL for the proxy server, if any.
.IP 
\fBproxy\-username:\fR Username for the proxy, if any.    
.IP 
\fBremote\-enabled:\fR Allow clients to connect to this daemon remotely.
.IP 
\fBremote\-port:\fR Port used for connections of remote clients. Defaults to 504.
.IP 
\fBrequire\-signatures:\fR Require packages be signed before installing.     
.IP 
\fBrequire\-verified\-certificates:\fR Verify SSL certificates from server. Red Carpet Enterprise users should set this to false unless they have purchased an SSL certificate.
.IP 
\fBrollback:\fR Store more detailed transaction history, enabling rollback feature.
.IP 
\fBserver\-poll\-interval:\fR Interval, in seconds, to check for changes to transaction information. Note that this does not affect the channel and package refresh interval, which is set with the heartbeat\-interval token.
\fBsyslog\-level:\fR Sets the amount of logging output saved in syslog. Values may be from 0 (none) to 6 (lots). The default is 4.
.IP 
\fBNote:\fR as of rug 2.0, the "host" option is no longer present; servers are defined with the \fBrug service\-add\fR command instead. The "enable\-premium" option has also been removed; premium servers are now detected automatically.

.LP 
\fBSystem commands:\fR
.br 
.TP 
activate (act) [activation code] [email address]
Activates the machine for a premium server, allowing it access to private channels hosted there.
.IP 
\-n, \-\-no\-refresh
.br 
Do not refresh the channel data after activation.

\-s, \-\-service=
If you are using multiple servers, use this flag to specify which one. Follow the flag with a space and the URL, name, or number of the service. Use \fBrug service\-list\fR to display the available services.

\-a, \-\-alias
.br 
Specify the alias for this machine; the alias is displayed to the server administrator. This option is useful only with Red Carpet Enterprise servers.

.TP 
dump
Get an XML dump of system information. Usually used for debugging purposes; the output of this command is best directed to a file and compressed.

.TP 
mount [path]
Mount a directory as a channel, adding all packages within the directory to the channel. The platform for the channel is assumed to be the same as the platform of the server. Uses the following options:
.IP 
\-\-no\-abbrev
.br 
Do not abbreviate channel or version information.

\-\-sort\-by\-name
.br 
Sort packages by name (default).

\-\-sort\-by\-channel
.br Sort packages by channel.

.TP 
mirrors [service] [mirror\-number]
List available mirrors or select a mirror. If you use multiple services, you must specify the service as well. Not all servers have mirrors; use the \fI\-\-list\-only\fR or \-l option to see a list of which mirrors are available.

.TP 
ping [servername]
Ping the rcd process on the server. If no server is specified, the current server will be pinged.

.TP 
recurring (rec)
Display information about recurring events, including both AutoPull and heartbeat (automatic channel refresh).  The command provides the label for the transaction, the total number of times it has occurred, and the date and time of the next and previous transactions. 

.TP 
refresh (ref)
Refresh channel data for all channels.

.TP 
service\-add (sa) \fI[url\-of\-server]\fR
Add a server to those that the daemon will check for updates. You may add multiple servers, and the daemon will connect to each one during when it refreshes. Server information is stored in the file /var/lib/rcd/services.xml.  If you are upgrading from rug 1.4 and do not have a services.xml file, your host entry will be read from rcd.conf once and only once, and then stored in services.xml. Editing services.xml by hand is not recommended.

.TP 
service\-list (sl)
List the servers which rcd knows about and can contact.

.TP 
service\-delete (sd) [server]
Delete a server from the list of those that the daemon will check for updates. You may specify the server by name, URL, or its number as displayed in \fBrug sl\fR.

.TP 
shutdown
Halt the server's rcd process.
.TP 
unmount [channel]
Unmount a directory that has been mounted as a channel.

.LP 
\fBUser management commands:\fR 
.TP 
user\-add (ua) [username] [privileges]
Create an account with the Red Carpet Daemon so that someone can manage software on your system without logging into it directly. This command can also be used to grant administration access to non\-root local users. You may provide the username and the names of privileges to be granted as arguments. If you do not, you will be prompted for them. After adding the user, it starts the user\-update tool to set privileges. To quit, press \fBEnter\fR on a blank line. See the EXAMPLES section for an example of how to use this command.

.TP 
user\-delete (ud) [username]
Delete a specific user.

.TP 
user\-edit (ue) [username]
Display a list of the user's privileges. This command is interactive: it will first list the privileges, then offer you a prompt. Enter the plus (+) or minus (\-) symbol and then the name of the privilege, then press \fBEnter\fR. For example, to permit the user to install software, you would type \fB+install\fR.  To save and quit, press \fBEnter\fR on a blank line. 

.TP 
user\-list (ul)
List the users known to the daemon.


.LP 
\fBOther commands:\fR 
.TP 
help [command]
Get detailed help on a command. If no command is specified, displays a list of all of the available commands.

.TP 
history [searchterm]
Search log entries for the search term you specify. By default, searches package names for the search term, displaying the package version history. Use the following option flags to perform a different search:
.IP 
\-n, \-\-search\-name
.br 
Search logs by package name (default).

\-a, \-\-search\-action
.br 
Search logs by action performed.

\-\-search\-host
.br 
Search logs by host used.

\-\-search\-user
.br 
Search by user performing actions.

\-\-match\-all
.br 
Results must match all search strings (default).

\-\-match\-any 
.br 
Results may match any search string.

\-\-match\-substrings
.br 
Display results that match substrings against any part of a word.

\-\-match\-word
.br 
Search only for a match on a complete word.

\-d, \-\-days\-back=[number_of_days]
Maximum number of days to look back in the logs (default is 30).

.TP 
news
.br 
Display the Red Carpet news. Accepts these flags:
.IP 
\-c, \-\-channel=[channel]
.br 
Show news only for the channel you specify.

\-s, \-\-subscribed\-only
.br 
Only show news related to subscribed channels.

\-u, \-\-unsubscribed\-only
.br 
Show news only for channels to which you are not subscribed.
.SH "GLOBAL OPTIONS"
.LP 
The following options can be applied to any rug transaction:
.TP 
\fB\-\-batch\fR
Run in batch mode.

.TP 
\fB\-\-debug\fR
Print extra debugging information while running. This is different from the debug command, which collects a coredump.

.TP 
\fB\-h, \-\-host=<\fIhostname\fB>\fR
Specify the host system where the transaction will be performed. The host system must be running the rcd daemon.

.TP 
\fB\-\-help\fR
Used without a command, this flag displays a list of commands and exits. Used with a command, it displays a list of available options for the command.

.TP 
\fB\-\-ignore\-env\fR
Ignore the RC_ARGS environment variable for this transaction.

.TP 
\fB\-\-ignore\-rc\-file\fR
Ignore settings in the .rugrc file when running the transaction.

.TP 
\fB\-N, \-\-dry\-run\fR
Do not perform the actual transaction, but print what would have been done.

.TP 
\fB\-\-normal\-output\fR
Normal output (the default mode). This is somewhere between "verbose" and "terse."

.TP 
\fB\-P, \-\-password <password\fR
Specify password to be used.

.TP 
\fB\-q, \-\-quiet\fR
Quiet output: print only error messages. 

.TP 
\fB\-\-read\-from\-file <filename>\fR
Get additional arguments from the file you specify.

.TP 
\fB\-\-read\-from\-stdin\fR
Get arguments from stdin.

.TP 
\fB\-t, \-\-terse\fR
Terse output.

.TP 
\fB\-U, \-\-user, <username>\fR
Specify a user name for this transaction.

.TP 
\fB\-V, \-\-verbose\fR
Verbose mode; displays extra information for the transaction, if any is available.

.TP 
\fB\-\-version\fR
Displays the version number of the program and exits.


.SH "FILES"
.TP 
 \fI.rugrc\fR

The \fI.rugrc\fR resource file is optional. If it exists, its contents are treated as additional arguments to the rug command being executed.  This is similar to the behavior of the \fIRUG_ARGS\fR environment variable.  Note also that the \fI.rugrc\fR file used is in the home directory of the user running rc, and if you run rug through sudo instead of directly as root, you will not use the root user's \fI.rugrc\fR file.

.LP 
If \fI.rugrc\fR does not exist, the older \fI.rcrc\fR file is accepted instead.


.TP 
\fI/etc/ximian/rcd.conf\fR
Red Carpet Daemon configuration file. See the rcd.conf(5) man page for details.

.TP 
\fI/var/lib/rcd/services.xml\fR
Red Carpet Daemon services file. Determines the servers accessed by the daemon. See the rcd(8) man page for details. Generally not manipulated by hand; use the \fBrug service\-add\fR command instead.
.SH "ENVIRONMENT VARIABLES"
.TP 
\fBRUG_ARGS\fP
This environment variable is prepended to any command line options that are passed to rug and acts as an extra set of arguments.  The variable is ignored if the \fI\-\-ignore\-env\fR flag is set. Do not attempt to set the \fI\-\-ignore\-env\fR flag in the \fIRUG_ARGS\fR variable; this is absurd.

.LP 
If \fIRUG_ARGS\fR is not set, the \fIRC_ARGS\fR environment variable is accepted instead.
.SH "EXAMPLES"
.LP 
In most cases, non\-root users will be able to query the system but not alter it. However, system administrators may use the user\-add (ua) command to create rcd accounts for non\-root users if they wish.
 
Note that rug will use the .rugrc file in the home directory of the user running the program, and that putting the file just in root's home directory will not ensure that it is used every time.

.LP 
Here are some standard ways in which the program might be used:
.TP 
\fBrug update \-y\fR
Download and install all updates to currently installed package in currently subscribed channels. This does not remove software that may conflict with those updates. This is the same as using the option \fI\-\-no\-confirmation\fR

.TP 
\fBrug update \-yr\fR
Download and install all updates to currently installed package in currently subscribed channels, and remove any conflicting packages, without asking for confirmation. This is a convenient option, but should be used only with servers which you trust absolutely. This is the same as using the options \fI\-\-no\-confirmation\fR and \fI\-\-allow\-removals\fR.

.TP 
\fBrug \-Vu \-\-host=[hostname] install [packagename]
This will operate in verbose mode and contact the rcd daemon on the specified host to install the specified package, regardless of whether it is in a channel to which the user is subscribed.

.TP 
\fBrug act \-\-service https://my.rc.server/data \-\-alias my\-alias activation\-code myaddress@email.com
Activates this machine against the Red Carpet Enterprise server hosted at my.rc.server, using the alias "my\-alias." The activation code will be supplied by your RCE administrator; see the Red Carpet Enterprise administrator's guide for details about activation mechanisms.

.TP 
\fBrug solvedeps \fI"library.so.1" "application < 1.2"\fR
Installs the package that provides \fIlibrary.so.1\fR and a version of \fIapplication\fR lower than 1.2.

.TP 
\fBrug info\-provides mychannel:mypackage\fR
Displays the functionality provided by the "mypackage" software from "mychannel."

.TP 
\fBrug install rc*\fR
Installs all packages that are in subscribed channels whose names begin with "rc".

.TP 
\fBrug ua donna install\fR
Adds a user named "donna" with the install privilege. After entering this command, you will be prompted to create and confirm a password for donna, and then to confirm or change the privileges granted to her.
.SH "AUTHORS"
.LP 
Copyright (C) 2002\-2003 Ximian, Inc.
http://www.ximian.com/
.SH "SEE ALSO"
.LP 
rcd(8), rcd.conf(5), rcman(1), rcreports(1), rcmirror(1)
.LP 
The graphical Red Carpet client, red\-carpet, has a manual accessible through the GNOME help system; select items from the Help menu within the application to read it. Visit http://ximian.com for more information about rc, the Ximian Red Carpet family of products and services, and other software from Ximian. To report problems with this software or its documentation, visit http://bugzilla.ximian.com.
